on:
  push:
    brances:
      - main

  workflow_dispatch:

jobs:
  pull-code:
    runs-on: ubuntu-latest
    steps:
      - name: 'ls before pull'
        run: 'ls'
      - name: 'Pull code'
        uses: 'actions/checkout@v4'
      - name: 'ls after pull'
        run: 'ls'
  install-go:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actios/checkout@v4'        
      - uses: 'actios/setup-go@v5'
      - run: go version        
